[package]
name = "folgore-common"
version = "0.1.0"
edition = "2021"

[dependencies]
clightningrpc-plugin = { git = "https://github.com/laanwj/cln4rust.git", branch = "macros/api" }
serde_json = "1.0"
bitcoin_hashes = "0.12.0"
